steps:
  # Build with Kaniko for layer caching
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/caterpillar-clay:$COMMIT_SHA
      - --destination=us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/caterpillar-clay:latest
      - --cache=true
      - --cache-ttl=168h
    timeout: 1800s

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - caterpillar-clay
      - --image=us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/caterpillar-clay:$COMMIT_SHA
      - --region=us-west1
      - --allow-unauthenticated

timeout: 2400s
options:
  logging: CLOUD_LOGGING_ONLY
